min_version = "2025.12.7"

[env]
PROJECT_NAME = "ha-pont-chaban-delmas"

_.python.venv = { path = ".venv" }

[tools]
pre-commit = { version = "4.5.0" }
uv = { version = "0.9.17" }

[settings]
python.uv_venv_auto = true

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''
