min_version = "2025.12.7"

[env]
PROJECT_NAME = "ha-pont-chaban-delmas"

[tools]
pre-commit = { version = "4.5.0" }
uv = { version = "0.9.17" }

[tasks.info]
description = "Print project information"
run = '''
echo "Project: $PROJECT_NAME"
echo "Virtual Environment: $VIRTUAL_ENV"
'''
