[project]
name = "pont-chaban-delmas"
version = "2025.12.0"
description = "HACS integration for Pont Chaban Delmas"
readme = "README.md"
requires-python = ">=3.13.2"
license = { text = "MIT" }
authors = [
  { name = "Jonathan Terral", email = "jterral@users.noreply.github.com" },
]
keywords = [
  "homeassistant",
  "hacs",
  "integration",
  "pont-chaban-delmas",
  "bordeaux",
]
dependencies = ["aiohttp>=3.13.2"]

[project.urls]
Homepage = "https://github.com/jterral/ha-pont-chaban-delmas"
Repository = "https://github.com/jterral/ha-pont-chaban-delmas"
Issues = "https://github.com/jterral/ha-pont-chaban-delmas/issues"

[dependency-groups]
dev = [
    "homeassistant>=2025.12.3",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.14.9",
]
